# Run me by typing `mythx analyze` in the directory of the yml file! :)

ci: true
confirm: true
analyze:
  mode: standard
  async: true
  create-group: true
  remappings:
    - "openzeppelin-contracts/=lib/openzeppelin-contracts/"
    - "openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/"
    - "prb-math/=lib/prb-math/src/"
    - "solady/=lib/solady/src/"
  targets:
    - src/issuer/BuyOrderIssuer.sol:BuyOrderIssuer
    - src/issuer/DirectBuyIssuer.sol:DirectBuyIssuer
    - src/issuer/OrderFees.sol:OrderFees
    - src/issuer/SellOrderProcessor.sol:SellOrderProcessor
    - src/BridgedERC20.sol:BridgedERC20
    - src/TransferRestrictor.sol:TransferRestrictor
