direction: right

Brokerage: {
  AAPL
  dAAPL
  SPX
  dSPX
  USD
  dUSD
}
Staking: {
  dAAPL
  dSPX
  dUSD
}
Staker
Trader
Distributor
Distributor.shape: diamond
Treasury

Brokerage.AAPL <-> Brokerage.dAAPL
Brokerage.SPX <-> Brokerage.dSPX
Brokerage.USD <-> Brokerage.dUSD

Brokerage -> Distributor: Fees
Distributor -> Staking: Fees
Distributor -> Treasury: Fees

Staker -> Staking: Stake dSPX
Staking -> Staker: Earn dSPX

Trader <-> Brokerage: dUSD
Trader <-> Brokerage: dSPX
