direction: right

veD Timelock
Voting: {
  shape: sql_table

  AAPL: 900k
  MSFT: 200k
  AMZN: 100k
}
Holder

Holder -> veD Timelock: lock D
veD Timelock -> Holder: receive veD
Holder -> Voting: vote veD
veD Timelock -> Holder: earn rewards
