[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
solc_version = '0.8.24'
evm_version = 'cancun'
via_ir = true
optimizer_runs = 2_000
gas_price = 200_000_000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
