[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
solc_version = '0.8.25'
evm_version = 'cancun'
optimizer_runs = 800
gas_price = 200_000_000
fs_permissions = [{ access = "read-write", path = "./"}]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
