[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
remappings = [
  "forge-std/=lib/forge-std/src/",
  "solady=lib/solady/src/",
  "solady-test=lib/solady/test/",
  "openzeppelin=lib/openzeppelin-contracts/contracts/",
  "prb-math=lib/prb-math/src/",
]

[rpc_endpoints]
arbitrum-goerli = "${ARBITRUM_GOERLI_RPC_URL}"

[etherscan]
arbitrum-goerli = { key = "${ARBISCAN_API_KEY}" }


# See more config options https://github.com/foundry-rs/foundry/tree/master/config
