[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
remappings = [
  "solady-test=lib/solady/test/",
]

[fuzz]
runs = 518

[rpc_endpoints]
sepolia = "${TEST_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }


# See more config options https://github.com/foundry-rs/foundry/tree/master/config
