[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
remappings = [
  "forge-std/=lib/forge-std/src/",
  "solady=lib/solady/src/",
  "solady-test=lib/solady/test/",
  "openzeppelin=lib/openzeppelin-contracts/contracts/",
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config