Apps: {
  Dinari Web
  Dinari Mobile
  External Wallets
}
Custody and Execution APIs
Brokerage Service
Brokerage Contracts

Apps -- Brokerage Contracts
Brokerage Contracts -- Brokerage Service
Brokerage Service -- Custody and Execution APIs
