direction: right

Traditional Market
Clearing House
Custodial Account
Dinari Brokerage
USDC/USD Pool
Certificate Token Minter
Users
DeFi

Traditional Market -- Clearing House: USD/AAPL
Clearing House -- Custodial Account: AAPL
Clearing House -- Dinari Brokerage: AAPL
Clearing House -- USDC/USD Pool: USD
Dinari Brokerage -- USDC/USD Pool: USDC
Dinari Brokerage -- Custodial Account: AAPL
Dinari Brokerage -- Certificate Token Minter: Mint/Burn
Users -- Dinari Brokerage: AAPL/USDC
Users -- DeFi: dAAPL
Certificate Token Minter -- Users: dAAPL
