Brokerage Order: {
  shape: sequence_diagram

  user: User Client App
  api: Dinari Brokerage Service
  contracts: Brokerage Smart Contracts
  clearing: Clearning House

  user -> api: Order w/ Payment Escrow
  api -> contracts: Submit Order and Escrow Payment
  api -> clearing: Order
  clearing -> api: Order Fulfillment
  api -> contracts: Mint/Burn Certificates
  contracts -> api: Payment Token Settlement
  api -> user: Notify User
}
