direction: right

Clearing House
Dinari Brokerage
USDC/USD Pool
Asset Token Contracts
Users

Clearing House -- Dinari Brokerage: AAPL/USD
Dinari Brokerage -- USDC/USD Pool: USDC/USD
Dinari Brokerage -- Asset Token Contracts: Mint/Burn dAAPL
Dinari Brokerage -- Asset Token Contracts: USDC
Asset Token Contracts -- Users: dAAPL/USDC
