Buy/Sell: {
  shape: sequence_diagram

  user: User
  wallet: User Wallet
  app: Client App
  rpc: Alchemy (RPC Node)
  contracts: Bridge Smart Contracts
  bot: Operator
  clearing: Clearing House

  app -> rpc: payToken.balanceOf(user)
  app -> rpc: payToken.allowance(user, bridge)
  app -> rpc: bridge.getFeesForOrder(...)
  Pre-sign Approval: {
    user -> app: Approve use of payToken
    app -> wallet: payToken.permit(user, bridge, ...)
    wallet -> user: Request to sign permit
    user -> wallet: Sign permit
    wallet -> app: Permit signature
  }
  Order Request: {
    user -> app: Submit order request
    app -> wallet: bridge.requestOrderWithPermit
    wallet -> user: Request to sign order
    user -> wallet: Sign order request
    wallet -> contracts: bridge.requestOrderWithPermit
    wallet -> contracts: Payment token escrowed
    contracts -> bot: Order details
  }
  Order Fulfillment: {
    bot -> clearing: Limit order
    clearing -> bot: Limit order fulfillment
    bot -> rpc: bridge.fillOrder
    rpc -> contracts: bridge.fillOrder
    contracts -> contracts: Fees taken
    contracts -> contracts: Fractional remainder swap
    contracts -> bot: Payment withdrawn
    contracts -> wallet: Mint/Burn dAsset tokens
  }
}
