name: deploy-stage

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  REGION: us-west-2

jobs:
  test:
    runs-on: ubuntu-latest
    environment: stage
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.REGION }}
          role-to-assume: ${{ vars.OIDC_ROLE_ARN }}
          role-session-name: ${{ github.actor }}

      - run: aws secretsmanager get-secret-value --secret-id ${{ vars.WEB3_DEPLOYMENTS_SECRETS_ID }} --query SecretString --output text | jq .default