name: deploy-prod

on:
  push:
    branches:
      - prod/**

permissions:
  id-token: write
  contents: read

env:
  REGION: us-west-2

jobs:
  deploy:
    environment: prod
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: v1.0.0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Enable corepack
        run: corepack enable

      - name: Install packages
        run: yarn install

      - name: Build node scripts
        run: yarn build

      - name: Build contracts
        run: forge build

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.REGION }}
          role-to-assume: ${{ vars.OIDC_ROLE_ARN }}
          role-session-name: ${{ github.actor }}

      - name: Deploy contracts
        run: ENVIRONMENT=production AWS_SECRET_ID=${{ vars.WEB3_DEPLOYMENTS_SECRETS_ID}} ./script/deploy.sh

      - uses: actions/upload-artifact@v4
        with:
          name: broadcast
          path: broadcast

      - uses: actions/upload-artifact@v4
        with:
          name: release
          path: release
